on: workflow_dispatch

name: azure-bicep-workshop-example

jobs:
  azure-bicep-workshop-example:
    runs-on: ubuntu-latest
    environment: dev
    env:
      ResourceGroupName: azure-bicep-workshop
      ResourceGroupLocation: westeurope
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          az group create --name ${{ env.ResourceGroupName }} --location ${{ env.ResourceGroupLocation }}
          echo "Azure resource group created"