on: [push]
name: azure-bicep-workshop

jobs:
  deploy-initial-resources:
    runs-on: ubuntu-latest
    environment: dev
    env:
      ResourceGroupName: azure-bicep-workshop
      ResourceGroupLocation: westeurope
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash

          az deployment group validate \
            -f ./templates/main.init.bicep \
            -p ./templates/parameters.init.example.json 

          az deployment group what-if \
              -f ./templates/main.init.bicep \
              -p ./templates/parameters.init.example.json 

          az deployment group create \
              -f ./templates/main.init.bicep \
              -p ./templates/parameters.init.example.json 
  deploy-all-resources:
    runs-on: ubuntu-latest
    environment: dev
    env:
      ResourceGroupName: azure-bicep-workshop
      ResourceGroupLocation: westeurope
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
                    
    - uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash

          az deployment group validate \
            -f ./templates/main.bicep \
            -p ./templates/parameters.example.json 

          az deployment group what-if \
              -f ./templates/main.bicep \
              -p ./templates/parameters.example.json 

          az deployment group create \
              -f ./templates/main.bicep \
              -p ./templates/parameters.example.json 
