on: [push]
name: azure-bicep-workshop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    env:
      ResourceGroupName: azure-bicep-workshop
      ResourceGroupLocation: westeurope
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: ARM-TTK
      # You may pin to the exact commit or the version.
      # uses: venura9/arm-ttk@39fe93a1875dfe86afcbd361a68466226f20aee4
      uses: venura9/arm-ttk@1.0
      with:
        # Path to run the tests on
        path: /
        # Run the test on a specific file on the path defined
        file: # optional
        # Test(s) to run, comma separated
        tests: # optional
        # Test(s) to be excluded, comma separated
        skip: # optional